#!/usr/bin/env python3
"""
Export one FastestDet TFLite image input as a C int8 array for MCU validation.

This script is intended for EDCP L4.1 validation:

1. Resize and quantize the same image used by the PC TFLite postprocess dry run.
2. Write a C header that can be copied into the GD32 generated firmware project.
3. Run TFLite inference and FastestDet decode once on the PC, so the MCU log can
   be compared against a known positive-input reference.

Usage:
    python tools/export_fastestdet_tflite_input_c_array.py \
      ./FastestDet_256.tflite \
      --image ./IMG_20251021_143157.jpg \
      --output ./fastestdet_l4_input.h
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence

from run_fastestdet_tflite_postprocess import (
    Detection,
    create_interpreter,
    decode_fastestdet,
    dequantize_output,
    dtype_name,
    load_image,
    output_to_hwc,
    quantization_text,
    quantize_input,
    read_class_names,
    sha256_file,
)
from run_fastestdet_tflite_vectors import tensor_summary


def import_numpy() -> Any:
    try:
        import numpy as np  # type: ignore
    except Exception as exc:  # pragma: no cover - depends on host environment
        raise RuntimeError("Missing dependency: numpy. Install it with `pip install numpy`.") from exc
    return np


def c_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def format_c_array(values: Sequence[int], values_per_line: int) -> str:
    lines: List[str] = []
    for start in range(0, len(values), values_per_line):
        chunk = values[start : start + values_per_line]
        lines.append("    " + ", ".join(str(int(value)) for value in chunk))
    return ",\n".join(lines)


def detection_comment(index: int, det: Detection) -> str:
    return (
        f" * DET idx={index} cls={det.class_id} name={det.class_name} "
        f"score={det.score:.6f} "
        f"x1={det.x1:.2f} y1={det.y1:.2f} x2={det.x2:.2f} y2={det.y2:.2f}"
    )


def detection_input_comment(
    index: int,
    det: Detection,
    image_size: Sequence[int],
    input_shape: Sequence[int],
) -> str:
    image_w, image_h = float(image_size[0]), float(image_size[1])
    input_h, input_w = float(input_shape[1]), float(input_shape[2])
    scale_x = input_w / image_w
    scale_y = input_h / image_h
    return (
        f" * DET_INPUT idx={index} cls={det.class_id} name={det.class_name} "
        f"score={det.score:.6f} "
        f"x1={det.x1 * scale_x:.2f} y1={det.y1 * scale_y:.2f} "
        f"x2={det.x2 * scale_x:.2f} y2={det.y2 * scale_y:.2f}"
    )


def write_header(
    path: Path,
    array_name: str,
    input_values: Sequence[int],
    result: Dict[str, Any],
    values_per_line: int,
) -> None:
    input_shape = result["input"]["shape"]
    summary = result["input_summary"]
    detections = [Detection(**item) for item in result["detections"]]
    guard = "FASTESTDET_L4_INPUT_H"

    lines: List[str] = [
        "/*",
        " * Auto-generated by tools/export_fastestdet_tflite_input_c_array.py.",
        " * Do not edit the array by hand; regenerate it from the original image.",
        " *",
        f" * MODEL={result['model_path']}",
        f" * MODEL_SHA256={result['model_sha256']}",
        f" * IMAGE={result['image_path']}",
        f" * ORIGINAL_SIZE={result['image_size']}",
        f" * CHANNEL_ORDER={result['channel_order']}",
        f" * INTERPOLATION={result['interpolation']}",
        f" * INPUT={result['input']['dtype']} {input_shape} {result['input']['quantization']}",
        f" * OUTPUT={result['output']['dtype']} {result['output']['shape']} "
        f"{result['output']['quantization']}",
        f" * INPUT_SUM={summary['sum']} INPUT_XOR=0x{summary['xor']:02X} "
        f"INPUT_MIN={summary['min']} INPUT_MAX={summary['max']}",
        f" * SCORE_THRESHOLD={result['score_threshold']} NMS_THRESHOLD={result['nms_threshold']}",
        f" * CANDIDATE_COUNT={result['candidate_count']} DET_COUNT={result['det_count']}",
    ]
    for index, det in enumerate(detections):
        lines.append(detection_comment(index, det))
    for index, det in enumerate(detections):
        lines.append(detection_input_comment(index, det, result["image_size"], input_shape))
    lines.extend(
        [
            " */",
            "",
            f"#ifndef {guard}",
            f"#define {guard}",
            "",
            "#include <stdint.h>",
            "",
            f"#define FASTESTDET_L4_INPUT_SIZE          {len(input_values)}U",
            f"#define FASTESTDET_L4_INPUT_BATCH         {int(input_shape[0])}U",
            f"#define FASTESTDET_L4_INPUT_HEIGHT        {int(input_shape[1])}U",
            f"#define FASTESTDET_L4_INPUT_WIDTH         {int(input_shape[2])}U",
            f"#define FASTESTDET_L4_INPUT_CHANNELS      {int(input_shape[3])}U",
            f"#define FASTESTDET_L4_INPUT_SUM           {summary['sum']}",
            f"#define FASTESTDET_L4_INPUT_XOR           0x{summary['xor']:02X}U",
            f"#define FASTESTDET_L4_INPUT_MIN           {summary['min']}",
            f"#define FASTESTDET_L4_INPUT_MAX           {summary['max']}",
            f"#define FASTESTDET_L4_EXPECT_CANDIDATES   {result['candidate_count']}U",
            f"#define FASTESTDET_L4_EXPECT_DETECTIONS   {result['det_count']}U",
            f"#define FASTESTDET_L4_MODEL_SHA256        \"{c_string(result['model_sha256'])}\"",
            "",
            f"static const int8_t {array_name}[FASTESTDET_L4_INPUT_SIZE] = {{",
            format_c_array(input_values, values_per_line),
            "};",
            "",
            f"#endif /* {guard} */",
            "",
        ]
    )

    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))


def build_result(args: argparse.Namespace) -> Dict[str, Any]:
    np = import_numpy()
    model_path = Path(args.model).resolve()
    image_path = Path(args.image).resolve()
    if not model_path.exists():
        raise FileNotFoundError(f"TFLite model not found: {model_path}")
    if not image_path.exists():
        raise FileNotFoundError(f"Image not found: {image_path}")

    runtime_name, interpreter = create_interpreter(model_path)
    interpreter.allocate_tensors()
    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()
    if len(input_details) != 1:
        raise RuntimeError(f"Expected one input tensor, got {len(input_details)}")
    if len(output_details) != 1:
        raise RuntimeError(f"Expected one output tensor, got {len(output_details)}")

    input_detail = input_details[0]
    output_detail = output_details[0]
    input_shape = [int(value) for value in input_detail["shape"]]
    if len(input_shape) != 4 or input_shape[0] != 1 or input_shape[-1] != 3:
        raise RuntimeError(f"Expected NHWC image input [1,H,W,3], got {input_shape}")
    if input_detail["dtype"] != np.int8:
        raise RuntimeError(f"Expected int8 TFLite input, got {dtype_name(input_detail['dtype'])}")

    input_h, input_w = input_shape[1], input_shape[2]
    original_image, resized_image, original_size = load_image(
        np,
        image_path,
        input_w,
        input_h,
        args.channel_order,
        args.interpolation,
    )
    del original_image

    input_tensor = quantize_input(np, resized_image, input_detail).reshape(tuple(input_shape))
    input_summary = tensor_summary(np, input_tensor)
    interpreter.set_tensor(input_detail["index"], input_tensor)
    interpreter.invoke()

    raw_output = interpreter.get_tensor(output_detail["index"])
    output = dequantize_output(np, raw_output, output_detail)
    feature_map, output_layout = output_to_hwc(output)
    class_names = read_class_names(Path(args.class_names).resolve() if args.class_names else None)
    candidates, detections = decode_fastestdet(
        feature_map,
        original_size,
        class_names,
        args.score_threshold,
        args.nms_threshold,
    )

    flat_input = [int(value) for value in input_tensor.reshape(-1)]
    return {
        "model_path": str(model_path),
        "model_bytes": model_path.stat().st_size,
        "model_sha256": sha256_file(model_path),
        "runtime": runtime_name,
        "image_path": str(image_path),
        "image_size": list(original_size),
        "channel_order": args.channel_order,
        "interpolation": args.interpolation,
        "input": {
            "name": input_detail.get("name", ""),
            "dtype": dtype_name(input_detail["dtype"]),
            "shape": input_shape,
            "quantization": quantization_text(input_detail),
        },
        "output": {
            "name": output_detail.get("name", ""),
            "dtype": dtype_name(output_detail["dtype"]),
            "shape": [int(value) for value in output_detail["shape"]],
            "layout": output_layout,
            "quantization": quantization_text(output_detail),
        },
        "input_summary": input_summary,
        "input_first32": flat_input[:32],
        "input_values": flat_input,
        "score_threshold": args.score_threshold,
        "nms_threshold": args.nms_threshold,
        "candidate_count": len(candidates),
        "det_count": len(detections),
        "detections": [det.__dict__ for det in detections],
    }


def print_human(result: Dict[str, Any], output_path: Path, array_name: str) -> None:
    summary = result["input_summary"]
    print("=== FILE ===")
    print(result["model_path"])
    print(f"bytes: {result['model_bytes']}")
    print(f"sha256: {result['model_sha256']}")
    print()
    print("=== IMAGE INPUT ===")
    print(result["image_path"])
    print(
        f"original_size={result['image_size']} "
        f"channel_order={result['channel_order']} "
        f"interpolation={result['interpolation']}"
    )
    print()
    print("=== TENSORS ===")
    print(
        "INPUT "
        f"name={result['input']['name']} "
        f"dtype={result['input']['dtype']} "
        f"shape={result['input']['shape']} "
        f"{result['input']['quantization']}"
    )
    print(
        "OUTPUT "
        f"name={result['output']['name']} "
        f"dtype={result['output']['dtype']} "
        f"shape={result['output']['shape']} "
        f"layout={result['output']['layout']} "
        f"{result['output']['quantization']}"
    )
    print()
    print("=== MCU HEADER ===")
    print(output_path)
    print(f"array={array_name} bytes={len(result['input_values'])}")
    print(
        f"IN_SUM={summary['sum']} IN_XOR=0x{summary['xor']:02X} "
        f"IN_MIN={summary['min']} IN_MAX={summary['max']}"
    )
    print("IN_FIRST32=" + ",".join(str(value) for value in result["input_first32"]))
    print()
    print("=== PC EXPECTED POSTPROCESS ===")
    print(
        f"SCORE_THRESHOLD={result['score_threshold']} "
        f"NMS_THRESHOLD={result['nms_threshold']} "
        f"CANDIDATE_COUNT={result['candidate_count']} "
        f"DET_COUNT={result['det_count']}"
    )
    for index, item in enumerate(result["detections"]):
        print(detection_comment(index, Detection(**item)).replace(" * ", "", 1))
    print()
    print("=== PC EXPECTED MODEL-SPACE DETECTIONS ===")
    for index, item in enumerate(result["detections"]):
        print(
            detection_input_comment(
                index,
                Detection(**item),
                result["image_size"],
                result["input"]["shape"],
            ).replace(" * ", "", 1)
        )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Export a FastestDet_256 TFLite image input as a C int8 header."
    )
    parser.add_argument("model", help="Path to FastestDet_256.tflite.")
    parser.add_argument("--image", required=True, help="Image path for the fixed MCU input.")
    parser.add_argument(
        "--output",
        default="fastestdet_l4_input.h",
        help="Output C header path. Default: fastestdet_l4_input.h",
    )
    parser.add_argument(
        "--array-name",
        default="fastestdet_l4_image_input",
        help="C array symbol name. Default: fastestdet_l4_image_input",
    )
    parser.add_argument(
        "--class-names",
        help="Optional class names file, one class per line. Defaults to EDCP weld classes.",
    )
    parser.add_argument(
        "--channel-order",
        choices=["bgr", "rgb"],
        default="bgr",
        help="Channel order after resize. Default matches OpenCV/FastestDet validation.",
    )
    parser.add_argument(
        "--interpolation",
        choices=["linear", "area", "nearest"],
        default="linear",
        help="Resize interpolation.",
    )
    parser.add_argument("--score-threshold", type=float, default=0.25)
    parser.add_argument("--nms-threshold", type=float, default=0.45)
    parser.add_argument("--values-per-line", type=int, default=16)
    parser.add_argument("--json", action="store_true", help="Print JSON summary instead of text.")
    return parser


def main(argv: Optional[Iterable[str]] = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        result = build_result(args)
        output_path = Path(args.output).resolve()
        write_header(
            output_path,
            args.array_name,
            result["input_values"],
            result,
            args.values_per_line,
        )
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    if args.json:
        printable = dict(result)
        printable.pop("input_values", None)
        printable["output_header"] = str(output_path)
        print(json.dumps(printable, ensure_ascii=False, indent=2))
    else:
        print_human(result, output_path, args.array_name)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
